name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  diagnostics:
    name: Diagnostics
    runs-on: test-runners
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # tag=v2.13.2
        with:
          egress-policy: block
          allowed-endpoints: >
            azure.archive.ubuntu.com:443
            azure.archive.ubuntu.com:80
            esm.ubuntu.com:443
            motd.ubuntu.com:443
            packages.microsoft.com:443
            ppa.launchpadcontent.net:443
            www.githubstatus.com:443

      - name: Check GitHub Status
        uses: crazy-max/ghaction-github-status@fa6ac37620bc5d44b93e15caed498629665e9ff5 # tag=v4.2.0
        with:
          overall_threshold: major
          packages_threshold: major_outage

      - name: Dump context
        uses: crazy-max/ghaction-dump-context@5355a8e5e6ac5a302e746a1c4b7747a0393863c8 # tag=v2.3.0

  Explore-GitHub-Actions:
    runs-on: test-runners
    steps:
      - run: echo "🎉 This job uses runner scale set runners!"
